.\" Copyright (c) 2017 Eric McCorkle
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd April 25, 2017
.Dt TRUST 7
.Os
.Sh NAME
.Nm trust
.Nd "trust system"
.Sh DESCRIPTION
The FreeBSD trust system is a system-level framework designed to
provide secure and verifiable chains of trust based on public-key
cryptographic signatures, provide facilities for secure loading and
verification of signed assets, and allow for the creation and
management of such signed assets.
.Pp
The trust system is designed foremost as a tamper-resilience
mechanism, designed to prevent unauthorized modification of critical
system components and to preserve a secure chain of custody from
.Xr loader 8
to the kernel and its modules, and possibly into user-mode
executables.  If used in conjunction with a secure boot mechanism
capable of providing a secure chain of custody up to either
.Xr loader 8
or the kernel, such as UEFI secure boot, coreboot/GRUB with signature
checking, or a similar mechanism, the combined system can provide a
very high degree of tamper-resilience at the OS level.
.Pp
In addition to its role as a tamper-resilience mechanism, the trust
system can function as a kind of root certificate authority, providing
a single root of trust for the entire system.
.Sh CONCEPTS
The trust system involves a number of concepts such as cryptographic
signatures, chains of trust, and others.  Understanding these concepts
is critical to understanding the functioning of the trust system.
.Ss Public and Private Keys
Public-key cryptographic signatures are essential to the functioning
of the trust system.  In public-key cryptography, key material
consists of two keys: a public key and a private key.  It is typically
possible to derive the corresponding public key given a private key;
however, a private key cannot be derived from a public key (this is
essential to the security properties of the system).  The combination
of a private key and its corresponding public key is called a keypair.
.Pp
In cryptographic signing, a signature is computed using a private key,
which can then be verified using the corresponding public key.  This
means that the public key can be distributed to anyone who wishes to
check signatures, while the private key can be kept safe so as to
prevent unauthorized parties from signing messages.
.Pp
The
.Xr openssl 1
library and toolchain provides mechanisms for generating and storing
keypairs.  Private keys are stored either as a standalone data
structure or as a PKCS#8 message.  Public keys are stored in a format
known as an X509 certificate.  The word
.Qq certificate
(or
.Qq
cert
for short) is often used to mean a
.Qq public key .
This certificate provides additional information such as a serial
number, who issued it, when it was issued, how it can be used, and
other information.
.Ss Certificate Chains
X509 public-key certificates may additionally bear signatures from
other keypairs, indicating that the certificate is trusted by the
signatory.  This is often used to delegate and/or restrict signing
authority, or to contain the effects of potential revocation of a
compromised key.  It can also be used to create ephemeral
.Qq one-shot
signing keys for a batch of requests.
.Pp
It is possible to organize three or more certificates such that the
first signs the second, the second signs the third, and so on.  Such
an arrangement is called a
.Qq certificate chain ,
and is an essential feature in trust systems such as this one.  If a
verifier possesses all certificates in a chain, they can use
cryptographic signature verification to trace the chain of trust back
to the first certificate.
.Ss Certificate Revocation
When signing keys are compromised, it becomes necessary to revoke
their validity so as to prevent signatures generated by the attacker
from being trusted.  This can be done using a special signed message
called a
.Qq certificate revocation list
(or CRL for short).  A CRL allows a signature previously issued by a
given keypair to be cancelled, thereby breaking any certificate chains
involving the signature.  Generating a CRL requires access to the
private key, as the revocation request must itself be signed.
.Ss Trust Origins
Any chain of trust must have an origin.  This is typically managed by
designating one or more certificates as a
.Qq root set .
Any certificate chain must link back to one of the certificates in the
root set in order to be trusted.
.Ss Signed Assets
The ultimate purpose of a chain of trust is to sign various assets,
thereby proving that they come from a trusted source and have not been
modified since being signed.  The
.Xr openssl 1
library supports several formats which can be used to sign assets
including the PKCS#7 message format, a subset of which is used by
FreeBSD trust system.
.Pp
Signing of executables and shared objects plays a critical role in
protecting chains of custody.  As such, the FreeBSD trust system makes
use of the
.Xr signed-elf 5
convention for signing Executable Linkable Format
.Pq Xr elf 5
binaries.  Additionally, it is sometimes necessary to protect
configuration files and scripts to maintain a protected chain of
custody (this is notably the case with
.Xr loader 8 ).
In such cases, the regular PKCS#7 envelope or detached signature
format can be used to sign such assets.
.Sh COMPONENTS
The trust system consists of a number of components, each of which
must interact properly for the trust system to be secure.  This
section describes each component and its function.
.Ss Trust Root Set
The
.Sy trust root set
is a set of public keys that serve as the origin of trust in the trust
system.  Any signature originating from one of these keys is
considered valid, and any certificate chain ending in one of these
keys is trusted.
.Pp
In order to preserve a chain of custody at boot time, it is necessary
to build the trust root set directly into the kernel and
.Xr loader 8
(and possibly other boot stages such as GRUB).  This set of keys is
known as the
.Sy builtin root set .
The builtin root set cannot be changed in a running system; in order
to add or remove keys in the trust root set, the system must be
rebuilt and restarted.  This is by design, as the trust root set
represents a critical security asset.
.Pp
The keys which comprise the trust root set are controlled by the trust root configuration (see
.Xr trust-config 7 ).
This configuration is also used by the build system to generate the
builtin root set.
.Ss Intermediate Key Store
While the trust root set must remain fixed for the duration of a
system's uptime, the trust system maintains a set of intermediate
trusted keys which can be added or removed without restarting the
system.
.Pp
The intermediate key store is maintained in such a state that all
intermediate keys have a valid signature chain back to one of the
trust root keys.  An intermediate key may be added to the trust system
only if it is signed by a trust root key or by an existing
intermediate key.  If a key in the intermediate set is removed, any
keys whose chain of trust depends on it are also removed.
.Ss Trust System Interface
The
.Sy trust system interface
provides a way for user-level programs to obtain the set of trusted
keys as well as add or remove keys to or from the intermediate key
store.
.Ss Trusted Signing Keys
The private keys that correspond to the public keys in the trust root
set are known as
.Sy trusted signing keys .
Trusted signing keys are used by tools such as
.Xr openssl 1
and
.Xr signelf 8
to produce signatures for intermediate keys or for signed assets.  See
.Xr trust-config 7
for details on the storage of trusted signing keys.

.Sh SEE ALSO
.Xr openssl 1 ,
.Xr signed-elf 5 ,
.Xr signelf 5 ,
.Xr trust-config 7
.Sh HISTORY
The trust system first appeared
.Fx 12.0 .
.Sh AUTHORS
This manual page was written by
.An Eric L. McCorkle Aq Mt emc2@metricspace.net .
