#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: trust_local_keygen
# REQUIRE: FILESYSTEMS trust_machine_keygen
# KEYWORD: nojail

. /etc/rc.subr

name="trust_local_keygen"
desc="Generate Local Intermediate Trust Keypair"
rcvar="trust_local_keygen_enable"
start_cmd="do_trust_local_keygen"
stop_cmd=":"

generate_keys()
{
        echo "Generating local intermediate trust keypair"
        openssl genpkey \
                -out /etc/trust/priv/local.pem \
                -algorithm ${trust_local_genpkey_alg} \
                ${trust_local_genpkey_opts}

        openssl req -new \
                -key /etc/trust/priv/local.pem \
                -out /etc/trust/reqs/local.csr \
                -subj ${trust_local_req_DN} \
                -days ${trust_local_req_days} \
                ${trust_local_req_opts}

        rm -f /etc/trust/reqs/local.ext
        touch /etc/trust/reqs/local.ext

        if [ ! -z "${trust_local_x509_key_usage}" ]; then
                echo "keyUsage=${trust_local_x509_key_usage}" >> \
                     /tmp/local.ext
        fi

        if [ ! -z "${trust_local_x509_ext_key_usage}" ]; then
                echo "extendedKeyUsage=${trust_local_x509_ext_key_usage}" >> \
                     /tmp/local.ext
        fi

        if [ ! -z "${trust_local_x509_extensions}" ]; then
                printf "${trust_local_x509_extensions}" >> \
                       /tmp/local.ext
        fi

        openssl x509 -req \
                -in /etc/trust/reqs/local.csr \
                -out /etc/trust/certs/local.pub.pem \
                -extfile /etc/trust/reqs/local.ext \
                -signkey ${trust_local_x509_signkey} \
                ${trust_local_x509_opts}

        rm /tmp/local.csr

}

do_trust_local_keygen()
{
        STARTDATE = `openssl x509
                             -enddate
                             -in /etc/trust/root/certs/local.pub.pem
                             -noout |
                     sed s/notAfter=//`
        ENDDATE = `openssl x509
                           -startdate
                           -in /etc/trust/root/certs/local.pub.pem
                           -noout |
                   sed s/notBefore=//`
        NOWSTAMP = `date -j -f "%a %b %d %T %Z %Y" "`date`" "+%s"`
        STARTSTAMP = `date -j -f "%b %d %T %Y %Z" "${STARTDATE}" "+%s"`
        ENDSTAMP = `date -j -f "%b %d %T %Y %Z" "${ENDDATE}" "+%s"`

        if [ -d /etc/trust/root/priv && \
             ! -f /etc/trust/priv/local.pem ]; then
                generate_keys
        elif [ ${NOWSTAMP} -lt ${STARTSTAMP}]; then
                echo "WARNING: local keypair is only valid in the future (${STARTDATE})"

                if [ ${trust_local_key_regen} ]; then
                        generate_keys
                fi
        elif [ ${NOWSTAMP} -gt ${ENDSTAMP} ]; then
                echo "WARNING: local keypair expired at ${ENDDATE}"

                if [ ${trust_local_key_regen} ]; then
                        generate_keys
                fi
        fi
}
