# $FreeBSD$

PACKAGE=lib${LIB}
LIB=            bdxl
SHLIB_MAJOR=    1
VERSION_DEF=    ${SRCTOP}/lib/libc/Versions.def
SYMBOL_MAPS=    ${.CURDIR}/Symbol.map

SRCS=
SRCS+=          bdxl_ast.c

INCS=
INCS+=		bdxl_types.h
INCS+=		bdxl_mirrors.h

.include <bsd.lib.mk>
